# Generated by Django 4.0.3 on 2022-04-05 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
