# Generated by Django 4.0 on 2022-01-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
    ]
