# Generated by Django 4.0 on 2022-01-16 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0003_remove_message_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='th_to_user', to='auth.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='th_from_user', to='auth.user')),
            ],
        ),
    ]
