# Generated by Django 4.0 on 2022-01-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_threadchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='thread_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.threadchat'),
            preserve_default=False,
        ),
    ]
