# Generated by Django 4.0 on 2022-01-18 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_thread_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadchat',
            name='recipent',
        ),
        migrations.RemoveField(
            model_name='threadchat',
            name='sender',
        ),
    ]
