# Generated by Django 4.0 on 2022-01-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0006_remove_threadchat_recipent_remove_threadchat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadchat',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threadchat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='auth.user'),
            preserve_default=False,
        ),
    ]
