# Generated by Django 4.0 on 2022-01-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_threadchat_to_user_threadchat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='thread_id',
            new_name='thread',
        ),
    ]
