# Generated by Django 4.0.3 on 2022-04-05 01:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bidang', models.CharField(max_length=3)),
                ('nama_bidang', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jabatan', models.CharField(max_length=3)),
                ('nama_jabatan', models.CharField(max_length=100)),
                ('bidang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.bidang')),
            ],
        ),
        migrations.CreateModel(
            name='Kantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kantor', models.CharField(max_length=3)),
                ('nama_kantor', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemilik', models.CharField(blank=True, max_length=100, null=True)),
                ('nik', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Format NIK Tidak Sesuai')])),
                ('jabatan', models.CharField(default='HRD', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,10})$', 'Format NO HP TIDAK SESUA!!!')])),
                ('npp', models.CharField(max_length=8)),
                ('nama_perusahaan', models.CharField(max_length=200)),
                ('nama_pic', models.CharField(max_length=100)),
                ('alamat', models.CharField(blank=True, max_length=250, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=5, null=True)),
                ('npwp_prsh', models.CharField(blank=True, max_length=15, null=True)),
                ('desa_kel', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('kota_kab', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenaga_kerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_kartu', models.CharField(max_length=11)),
                ('no_hp', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,10})$', 'Format NO HP TIDAK SESUA!!!')])),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('tgl_lahir', models.DateField()),
                ('tgl_keps', models.DateField()),
                ('tgl_na', models.DateField(blank=True, null=True)),
                ('npp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.perusahaan')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,10})$', 'Format NO HP TIDAK SESUA!!!')])),
                ('status', models.BooleanField(default=False)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.jabatan')),
                ('kode_kantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.kantor')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='pembina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.profile'),
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='informasi/attachment')),
                ('isi', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
