# Generated by Django 4.0 on 2021-12-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jabatan',
            table='JABATAN',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
