# Generated by Django 4.0 on 2022-03-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
