# Generated by Django 4.0 on 2022-01-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='kode_pos',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='nama_pic',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perusahaan',
            name='npwp_prsh',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
