# Generated by Django 4.0 on 2021-12-14 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perusahaan',
            name='no_hp',
            field=models.CharField(default=1, max_length=13, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,10})$', 'Format NO HP TIDAK SESUA!!!')]),
            preserve_default=False,
        ),
    ]
