# Generated by Django 4.0 on 2021-12-15 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasi',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.profile'),
            preserve_default=False,
        ),
    ]
