# Generated by Django 4.0 on 2021-12-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bidang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.bidang'),
            preserve_default=False,
        ),
    ]
