# Generated by Django 4.0 on 2021-12-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0002_alter_jabatan_table_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='informasi',
            table='DAFTAR INFORMASI',
        ),
        migrations.AlterModelTable(
            name='perusahaan',
            table='DAFTAR PERUSAHAAN',
        ),
        migrations.AlterModelTable(
            name='tenaga_kerja',
            table='DAFTAR TK',
        ),
    ]
