# Generated by Django 4.0 on 2022-01-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0002_perusahaan_kode_pos_perusahaan_nama_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perusahaan',
            old_name='nama',
            new_name='nama_pemilik',
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='nama_pic',
            field=models.CharField(max_length=100),
        ),
    ]
