# Generated by Django 4.0 on 2022-01-28 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0002_alter_perusahaan_email_alter_perusahaan_npwp_prsh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaan',
            name='no_hp',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^(08+[1-9])([0-9]{7,10})$', 'Format NO HP TIDAK SESUA!!!')]),
        ),
    ]
