# Generated by Django 4.0 on 2021-12-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0003_alter_informasi_table_alter_perusahaan_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='informasi',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jabatan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='kantor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='perusahaan',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenaga_kerja',
            table=None,
        ),
    ]
