# Generated by Django 4.0 on 2022-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0003_alter_perusahaan_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaan',
            name='alamat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='desa_kel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='kota_kab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='nama_pemilik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
