# Generated by Django 4.0 on 2022-02-21 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0004_alter_perusahaan_alamat_alter_perusahaan_desa_kel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perusahaan',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Format NIK Tidak Sesuai')]),
        ),
    ]
