# Generated by Django 4.0 on 2021-12-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kepesertaan', '0004_alter_informasi_npp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informasi',
            name='npp',
        ),
        migrations.AddField(
            model_name='informasi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
