# Generated by Django 4.0 on 2021-12-16 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0004_alter_informasi_table_alter_jabatan_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_bidang', models.CharField(max_length=3)),
                ('nama_bidang', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='bidang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.bidang'),
            preserve_default=False,
        ),
    ]
