# Generated by Django 4.0 on 2021-12-27 03:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0005_remove_informasi_npp_informasi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasi',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage(location='/media/informasi/attachment')),
        ),
    ]
