# Generated by Django 4.0 on 2022-03-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0005_alter_perusahaan_nik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='perusahaan',
            name='npp',
            field=models.CharField(max_length=8),
        ),
    ]
