# Generated by Django 4.0 on 2022-03-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0005_alter_perusahaan_nik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
