# Generated by Django 4.0 on 2022-03-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0006_remove_profile_email'),
        ('kepesertaan', '0006_remove_profile_email_alter_perusahaan_npp'),
    ]

    operations = [
    ]
