# Generated by Django 4.0 on 2021-12-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0008_alter_informasi_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasi',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='informasi/attachment'),
        ),
    ]
