# Generated by Django 4.0 on 2022-01-17 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kepesertaan', '0002_perusahaan_kode_pos_perusahaan_nama_pic_and_more'),
        ('kunjungan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_kunjungan',
            name='to_perusahaan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kepesertaan.perusahaan'),
            preserve_default=False,
        ),
    ]
