# Generated by Django 4.0 on 2022-02-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kunjungan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='approval_bak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('berita_acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunjungan.berita_kunjungan')),
            ],
        ),
    ]
