# Generated by Django 4.0 on 2022-02-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunjungan', '0002_approval_bak'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita_kunjungan',
            name='qrcode_pembina',
            field=models.ImageField(default=1, upload_to='media/kunjungan/pembina/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='berita_kunjungan',
            name='qrcode_to_nama',
            field=models.ImageField(default=1, upload_to='media/kunjungan/toNama/'),
            preserve_default=False,
        ),
    ]
