# Generated by Django 4.0 on 2022-02-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kunjungan', '0003_berita_kunjungan_qrcode_pembina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita_kunjungan',
            name='qrcode_pembina',
        ),
        migrations.RemoveField(
            model_name='berita_kunjungan',
            name='qrcode_to_nama',
        ),
    ]
