# Generated by Django 4.0 on 2022-02-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kunjungan', '0004_remove_berita_kunjungan_qrcode_pembina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval_bak',
            name='approved',
        ),
        migrations.AddField(
            model_name='approval_bak',
            name='status',
            field=models.CharField(choices=[('0', 'PROSES'), ('1', 'SETUJU'), ('2', 'DITOLAK')], default='0', max_length=1),
        ),
    ]
